# Generated by Django 3.2.5 on 2021-08-01 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='casesperdistrict',
            options={'ordering': ['-date', 'cases']},
        ),
        migrations.RemoveField(
            model_name='coviddata',
            name='local_context',
        ),
        migrations.AddField(
            model_name='coviddata',
            name='context',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterUniqueTogether(
            name='casesperdistrict',
            unique_together={('district', 'date')},
        ),
    ]
