# Generated by Django 3.2.5 on 2021-08-15 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0002_auto_20210801_1807'),
    ]

    operations = [
        migrations.AddField(
            model_name='coviddata',
            name='event_type',
            field=models.CharField(choices=[('1', 'PA'), ('2', 'EV')], default='2', max_length=3),
        ),
    ]
