# Generated by Django 3.2.5 on 2021-08-15 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0005_alter_coviddata_event_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coviddata',
            name='event_type',
            field=models.CharField(choices=[('1', 'PA'), ('2', 'EV')], max_length=3),
        ),
    ]
