# Generated by Django 3.2.5 on 2021-08-15 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0006_alter_coviddata_event_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coviddata',
            name='event_type',
        ),
    ]
