# Generated by Django 3.2.5 on 2021-09-10 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0007_remove_coviddata_event_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coviddata',
            options={'ordering': ['-date']},
        ),
    ]
