# Generated by Django 3.2.5 on 2021-11-01 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0009_auto_20211018_1025'),
    ]

    operations = [
        migrations.CreateModel(
            name='SentimentAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
                ('sentence', models.CharField(max_length=500, unique=True)),
                ('analysis', models.CharField(max_length=100, unique=True)),
                ('impact', models.CharField(max_length=100, unique=True)),
                ('aspects', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ['date'],
            },
        ),
    ]
