# Generated by Django 3.2.5 on 2021-11-01 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0010_sentimentanalysis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sentimentanalysis',
            name='analysis',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sentimentanalysis',
            name='aspects',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sentimentanalysis',
            name='impact',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
